### ISSUE TITLE
Static vs non-static

### ISSUE THREAD

**Issue by Frederiklw** [Kagemann/PCSS_GameClient#34]
Kan du ikke lige kigge på om startGame i IntroState boolean kan være static? Den styrer baggrundstint og at man ikke kan trykke på knapperne samtidig. Den sættes false når man i lobbyState trykker back.

**Comment by AndersElmholdt** [comment]
Global variables i states kan sagtens være static, da der ikke er noget behov for at have variablerne bundet til specifikke objekter, da der kun er 1 objekt af hver state.
